### ISSUE TITLE
Set layout for authors

### ISSUE THREAD

**Issue by MichaelCurrin** [cloverlearn/cloverx#2]
If you set up `defaults` in your config` you can make `type: author` get an appropriate layout.

https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/jekyll/configuration/frontmatter-defaults.html

Page with no layout:

https://www.cloverlearn.com/authors/yasas.html

https://github.com/cloverlearn/cloverx/blob/main/_authors/yasas.md

**Comment by ysenarath** [comment]
Thanks for the suggestions and your guidance. Fix by updating _config.yml. Thank you.
